// Loads the wasm module on mount, constructs a Simulator instance, and
// exposes it (plus loading/error state) to the rest of the app.

import { useCallback, useEffect, useRef, useState } from "react";
// The pkg/ directory is generated by `npm run build:wasm`. wasm-pack creates
// a TS declaration file alongside the JS glue.
import init, { Simulator } from "../../pkg/biosim4_wasm.js";

export interface UseSimulatorState {
  simulator: Simulator | null;
  loading: boolean;
  error: string | null;
  /** Increments every time the simulator is replaced (e.g. on reset/reconfig). */
  generation_token: number;
}

export interface UseSimulatorAPI extends UseSimulatorState {
  reload: (configJson?: string) => Promise<void>;
}

export function useSimulator(initialConfigJson = ""): UseSimulatorAPI {
  const [state, setState] = useState<UseSimulatorState>({
    simulator: null,
    loading: true,
    error: null,
    generation_token: 0,
  });
  const wasmReadyRef = useRef<Promise<unknown> | null>(null);

  const load = useCallback(async (configJson: string = initialConfigJson) => {
    setState((s) => ({ ...s, loading: true, error: null }));
    try {
      // Initialise the wasm module once. Re-entering init() with no args is
      // safe: wasm-pack's init returns the cached module.
      if (!wasmReadyRef.current) {
        wasmReadyRef.current = init();
      }
      await wasmReadyRef.current;
      const sim = new Simulator(configJson);
      setState((s) => ({
        simulator: sim,
        loading: false,
        error: null,
        generation_token: s.generation_token + 1,
      }));
    } catch (e) {
      setState((s) => ({
        ...s,
        loading: false,
        error: e instanceof Error ? e.message : String(e),
      }));
    }
  // initialConfigJson is intentionally excluded: it is only read at mount time.
  // Callers use reload(json) to reconfigure.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    void load(initialConfigJson);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return { ...state, reload: load };
}
