pub mod types;
pub mod rng;
pub mod sim_config;
pub mod registry;
pub mod genome;
pub mod grid;
pub mod signals_layer;
pub mod food_layer;
pub mod barriers;
pub mod agent;
pub mod population;
pub mod world;
pub mod sensors;
pub mod actions;
pub mod challenges;
pub mod sim_state;
pub mod sim_step;
pub mod spawn;
pub mod analysis;

pub use types::{Coord, Dir};
pub use sim_config::SimConfig;
pub use sim_state::SimulationState;
pub use sim_step::{step_generation, step_one};
pub use spawn::{initialize_generation_0, spawn_new_generation};
pub use analysis::{EpochStats, collect_epoch_stats, print_epoch_stats};
